In [1]:
import numpy as np
import matplotlib.pyplot as pp

##### Create a NumPy array

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

##### Identify the datatype of the array

In [3]:
a.dtype

dtype('int64')

##### Creating a NumPy array with the specific datatype

In [4]:
a = np.array([1,2,3,4,5], dtype = np.float64)
a

array([ 1.,  2.,  3.,  4.,  5.])

In [6]:
a.dtype

dtype('float64')

##### No of dimensions, shape and size

In [7]:
a.ndim, a.shape, a.size

(1, (5,), 5)

##### Create a 2 dimensional array

In [12]:
b = np.array([[11,12,13,14,15],[16,17,18,19,20]], dtype = np.float64)
b

array([[ 11.,  12.,  13.,  14.,  15.],
       [ 16.,  17.,  18.,  19.,  20.]])

In [13]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

##### Create an array of zeroes

In [29]:
np.zeros((3,3),'d')

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

##### Create an empty array

In [33]:
np.empty((4,4),'d')

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

##### Create a linearly spaced array

In [35]:
np.linspace(0,20,7)

array([  0.        ,   3.33333333,   6.66666667,  10.        ,
        13.33333333,  16.66666667,  20.        ])

##### Create an array with step - '3' in this case

In [38]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

##### Create a random number

In [41]:
np.random.standard_normal((2,4))

array([[ 0.71553345,  0.0595416 , -0.41502245,  0.22592092],
       [ 0.42233522, -1.52343744, -0.69520794, -0.09140069]])

##### Combine two arrays

In [44]:
a = np.random.standard_normal((3,4))
b = np.random.standard_normal((3,4))

In [46]:
np.vstack([a,b])

array([[-0.41772451, -1.14317397, -0.16870363, -0.47244098],
       [ 0.94292462,  1.08987845,  0.18661591, -0.88850554],
       [-0.97784691,  0.04198857,  0.64616939, -0.29835169],
       [-1.49534358, -1.06455231, -1.38552479,  0.68948963],
       [ 1.32304388,  0.78086948, -0.24174931,  0.95940881],
       [-0.73609612, -0.72939653,  0.08622781, -1.18547089]])

In [47]:
np.hstack([a,b])

array([[-0.41772451, -1.14317397, -0.16870363, -0.47244098, -1.49534358,
        -1.06455231, -1.38552479,  0.68948963],
       [ 0.94292462,  1.08987845,  0.18661591, -0.88850554,  1.32304388,
         0.78086948, -0.24174931,  0.95940881],
       [-0.97784691,  0.04198857,  0.64616939, -0.29835169, -0.73609612,
        -0.72939653,  0.08622781, -1.18547089]])

In [48]:
a.transpose()

array([[-0.41772451,  0.94292462, -0.97784691],
       [-1.14317397,  1.08987845,  0.04198857],
       [-0.16870363,  0.18661591,  0.64616939],
       [-0.47244098, -0.88850554, -0.29835169]])

##### Save and Load

In [50]:
np.save('array_Manipulation.npy',a)

In [51]:
aload = np.load('array_Manipulation.npy')

In [52]:
aload

array([[-0.41772451, -1.14317397, -0.16870363, -0.47244098],
       [ 0.94292462,  1.08987845,  0.18661591, -0.88850554],
       [-0.97784691,  0.04198857,  0.64616939, -0.29835169]])