## Index and Slice NumPy Arrays

In [53]:
import numpy as np

### Indexing

##### Build a 1-dimensional NumPy Array

In [108]:
v = np.linspace(0,10,5)
v

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [109]:
v[0]

0.0

In [110]:
v[4]

10.0

In [111]:
v[-1]

10.0

##### Build a 2-dimensional NumPy Array

In [75]:
vv = np.random.random((5,4))
vv

array([[ 0.48955001,  0.90142202,  0.36869306,  0.86417191],
       [ 0.63307079,  0.73502751,  0.52928266,  0.67224334],
       [ 0.81270387,  0.00983457,  0.6291634 ,  0.97049743],
       [ 0.48245027,  0.78593978,  0.5580567 ,  0.52740425],
       [ 0.59829759,  0.68524608,  0.75667218,  0.48325626]])

In [76]:
vv[0,0]

0.48955001353089067

In [77]:
vv[1,2]

0.52928266389836831

##### Build a 2-dimensional array with Python lists (list of lists)

In [70]:
ll = [[1,2,3],[4,5,6],[7,8,9]]
ll

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [71]:
ll[1,2]

TypeError: list indices must be integers or slices, not tuple

In [72]:
ll[1][2]

6

### Slicing

   ##### Slicing one dimensional array using NumPy

In [101]:
v[2:4]

array([ 0. ,  7.5])

##### Slicing two dimensional array using NumPy

In [102]:
vv[2:5,1]

array([ 0.00983457,  1.57187957,  1.37049217])

In [103]:
vv[2:5,1:2]

array([[ 0.00983457],
       [ 1.57187957],
       [ 1.37049217]])

In [104]:
vv[2:-1,:]

array([[ 1.62540775,  0.00983457,  1.2583268 ,  1.94099485],
       [ 0.48245027,  1.57187957,  1.11611339,  1.0548085 ]])

##### Stepping through every 2nd Item

In [105]:
vv[:,::2]

array([[ 0.48955001,  0.36869306],
       [ 1.26614159,  1.05856533],
       [ 1.62540775,  1.2583268 ],
       [ 0.48245027,  1.11611339],
       [ 1.19659517,  1.51334437]])

##### In NumPy slicing, we end up modifying the original array when we create a new array by slicing bcos NumPy slices yield views to the same piece of memory

In [112]:
v2 = v[2:4]
v2

array([ 5. ,  7.5])

In [113]:
v2[0] = 0

In [114]:
v2[0]

0.0

##### In the original array also, the value has changed

In [88]:
v[0]

0.0

##### Create a copy explicitly in NumPy to not make change in the original array

In [117]:
v3 = v[2:4].copy()
v3

array([ 0. ,  7.5])

In [118]:
v3[0]=5
v3

array([ 5. ,  7.5])

In [120]:
v[:]

array([  0. ,   2.5,   0. ,   7.5,  10. ])

### Advanced Indexing

##### 1) Use a list of Indices or NumPy array of indices to select only certain Elements

In [94]:
v[[1,2,3]]

array([ 2.5,  0. ,  7.5])

##### 2) Use an array of boolean values- true or false, to choose which elements to include and which not to.

In [121]:
v>0

array([False,  True, False,  True,  True], dtype=bool)

##### Assign the result of the above comparison to another array and use that array to index v

In [96]:
bool_index = v>0

In [122]:
v[bool_index]

array([  2.5,   7.5,  10. ])

##### Operate only on the part of the 2-dimensional array - vv

In [98]:
vv[vv>0.5]

array([ 0.90142202,  0.86417191,  0.63307079,  0.73502751,  0.52928266,
        0.67224334,  0.81270387,  0.6291634 ,  0.97049743,  0.78593978,
        0.5580567 ,  0.52740425,  0.59829759,  0.68524608,  0.75667218])

In [124]:
vv[vv>0.5] = vv[vv>0.5] *2

In [123]:
vv

array([[ 0.48955001,  1.80284404,  0.36869306,  1.72834381],
       [ 1.26614159,  1.47005502,  1.05856533,  1.34448667],
       [ 1.62540775,  0.00983457,  1.2583268 ,  1.94099485],
       [ 0.48245027,  1.57187957,  1.11611339,  1.0548085 ],
       [ 1.19659517,  1.37049217,  1.51334437,  0.48325626]])